[nltk_data] Error loading punkt: <urlopen error Remote end closed
[nltk_data]     connection without response>
Traceback (most recent call last):
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2/aib232074/train_model.py", line 653, in <module>
    main()
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2/aib232074/train_model.py", line 578, in main
    json_val = sys.agrv[2]
AttributeError: module 'sys' has no attribute 'agrv'
[nltk_data] Error loading punkt: <urlopen error Remote end closed
[nltk_data]     connection without response>
/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2/aib232074/test_model.py:111: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:261.)
  test_data = TensorDataset(torch.tensor(combined_embeddings), torch.tensor(labels))
Traceback (most recent call last):
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2/aib232074/test_model.py", line 536, in <module>
    main()
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2/aib232074/test_model.py", line 434, in main
    col_model.load_state_dict(torch.load("Predict_col_Model.pth", map_location=torch.device('cpu')))
  File "/home/cse/dual/cs5190443/scratch/anaconda3/envs/a100s2/lib/python3.9/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/cse/dual/cs5190443/scratch/anaconda3/envs/a100s2/lib/python3.9/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/cse/dual/cs5190443/scratch/anaconda3/envs/a100s2/lib/python3.9/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'Predict_col_Model.pth'
Traceback (most recent call last):
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2/evaluate_submission.py", line 12, in <module>
    sub_file = [json.loads(x) for x in open(submission_file)]
FileNotFoundError: [Errno 2] No such file or directory: 'aib232074/predictions_new.jsonl'
