Traceback (most recent call last):
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2/cs1210557/a2.py", line 387, in <module>
    inference(sys.argv[2],sys.argv[3])
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2/cs1210557/a2.py", line 358, in inference
    cs = predictions(valquestions,valcols)
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2/cs1210557/a2.py", line 337, in predictions
    model.load_state_dict(torch.load('/colSelector.pth', map_location=device))
  File "/home/cse/dual/cs5190443/scratch/anaconda3/envs/v100/lib/python3.9/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/cse/dual/cs5190443/scratch/anaconda3/envs/v100/lib/python3.9/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/cse/dual/cs5190443/scratch/anaconda3/envs/v100/lib/python3.9/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/colSelector.pth'
Traceback (most recent call last):
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2/evaluate_submission.py", line 12, in <module>
    sub_file = [json.loads(x) for x in open(submission_file)]
FileNotFoundError: [Errno 2] No such file or directory: 'cs1210557/predictions_new.jsonl'
