bash: run_model.sh: No such file or directory
bash: run_model.sh: No such file or directory
Traceback (most recent call last):
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2_resub/evaluate_submission.py", line 12, in <module>
    sub_file = [json.loads(x) for x in open(submission_file)]
FileNotFoundError: [Errno 2] No such file or directory: 'mt6190763/predictions_new.jsonl'
Traceback (most recent call last):
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2_resub/mt6190763/train.py", line 223, in <module>
    with open('2019MT60763/vocab.json','w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '2019MT60763/vocab.json'
Traceback (most recent call last):
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2_resub/mt6190763/test.py", line 63, in <module>
    Unzipping_the_data('2019MT60763.zip' , '2019MT60763')
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2_resub/mt6190763/test.py", line 60, in Unzipping_the_data
    with zipfile.ZipFile(Zip_path, 'r') as fp:
  File "/home/cse/dual/cs5190443/scratch/anaconda3/envs/v100/lib/python3.9/zipfile.py", line 1250, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '2019MT60763.zip'
Traceback (most recent call last):
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2_resub/evaluate_submission.py", line 12, in <module>
    sub_file = [json.loads(x) for x in open(submission_file)]
FileNotFoundError: [Errno 2] No such file or directory: 'mt6190763/predictions_new.jsonl'